### ISSUE TITLE
Easier access to older versions

### ISSUE THREAD

**Issue by druesendieb** [dell/csm-docs#26]
Hi folks,

it took me quite some time to find the link to the documentation of older driver versions which is placed on the introduction page. 
I think a `Version` dropdown item in the top menu (similar to the one at  kubernetes.io) would really increase the accessibility of the documentation. 

Kind regards

**Comment by prablr79** [comment]
@druesendieb  Thank you for the valuable feedback, we will consider this in next release.

**Comment by druesendieb** [comment]
Thanks a lot 🙇 
I would love to be able to give feedback to the unity drivers helm chart as well, but sadly issues are deactivated in the repository.

BR

**Comment by shanmydell** [comment]
> Thanks a lot 🙇
> I would love to be able to give feedback to the unity drivers helm chart as well, but sadly issues are deactivated in the repository.
> 
> BR

@druesendieb Please raise an issue in this portal, it will be addressed.

**Comment by shanmydell** [comment]
@druesendieb : The enhancement has been implemented
